get_pkgbuild doesn't need to know arch
Signed-off-by: Gabriel Souza Franco <gabrielfrancosouza@gmail.com>

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -79,20 +79,20 @@ for repo in ${repos[@]}; do
 		_pkgver=$(getpkgver "$pkgfile")
 		_pkgarch=$(getpkgarch "$pkgfile")
 
-		get_pkgbuild $repo $_pkgbase $_pkgarch $_pkgver || die "PKGBUILD not found for $_pkgbase-$_pkgver"
+		get_pkgbuild $repo $_pkgbase $_pkgver || die "PKGBUILD not found for $_pkgbase-$_pkgver"
 
-		_pkgnames=($(. "$WORKDIR/pkgbuilds/$repo-$_pkgarch/$_pkgbase-$_pkgver"; echo ${pkgname[@]}))
+		_pkgnames=($(. "$WORKDIR/pkgbuilds/$repo/$_pkgbase-$_pkgver"; echo ${pkgname[@]}))
 		_pkgentry=($(arch_history_fetch $repo $_pkgname $_pkgarch))
 		if [ "${#_pkgentry[@]}" -eq 2 ]; then
 			_db_ver=${_pkgentry[1]}
 
-			get_pkgbuild $repo $_pkgbase $_pkgarch $_db_ver || die "PKGBUILD not found for $_pkgbase-$_db_ver"
+			get_pkgbuild $repo $_pkgbase $_db_ver || die "PKGBUILD not found for $_pkgbase-$_db_ver"
 
-			_db_names=($(. "${WORKDIR}/pkgbuilds/${repo}-${_pkgarch}/${_pkgbase}-${_db_ver}"; echo ${pkgname[@]}))
+			_db_names=($(. "${WORKDIR}/pkgbuilds/${repo}/${_pkgbase}-${_db_ver}"; echo ${pkgname[@]}))
 
 			# duplicate ${_pkgnames[@]} to make uniq_array only return entries only found in ${_db_names[@]}
 			for _pkg in $(uniq_array ${_pkgnames[@]} ${_pkgnames[@]} ${_db_names[@]}); do
-				_rarchs=($(. "${WORKDIR}/pkgbuilds/${repo}-${_pkgarch}/${_pkgbase}-${_db_ver}"; get_arch))
+				_rarchs=($(. "${WORKDIR}/pkgbuilds/${repo}/${_pkgbase}-${_db_ver}"; get_arch))
 				for _rarch in ${_rarchs[@]}; do
 					pkgs_to_remove[$_pkg-$_rarch]=''
 				done
